/*
  File: layout.tsx
  Description: Simply contains the layout with only the children elements for optional extension to multiple pages in the future

  Responsible: Alex Miller
*/

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
